general {
    before_sleep_cmd = /usr/bin/openrgb --profile off; loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on; /usr/bin/openrgb --profile wallust-theme; python ~/scripts/open_rgb_script.py >> ~/logs.txt  # to avoid having to press a key twice to turn on the display.
}
