general {
    before_sleep_cmd = /usr/bin/openrgb --profile off --noautoconnect;  qs -c noctalia-shell ipc call lockScreen lock; 
    after_sleep_cmd = hyprctl dispatch dpms on; /usr/bin/openrgb --profile wallust-theme; python ~/scripts/open_rgb_script.py >> ~/logs.txt  # to avoid having to press a key twice to turn on the display.
}
listener {
    timeout =  300
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
listener {
    timeout =  450
    on-timeout = qs -c noctalia-shell ipc call lockScreen lock;
}
listener {
    timeout = 600
    on-timeout = systemctl suspend                # suspend pc
}
